### ISSUE TITLE
Non-static method 'createConversation' should not be called statically

### ISSUE THREAD

**Issue by dzatona** [musonza/chat#106]
Any pieces of advice?

![Screenshot](https://msk-ix.s3.amazonaws.com/o4lv8.png)

**Comment by musonza** [comment]
Did you import `chat` at the top `use Musonza\Chat\Chat` at the top? or if you have the facade set you can import as `use Chat`

**Comment by jonaspoelmans** [comment]
I have the same issue. I imported the class at the top of the page as you mentioned. Any other issue that might be causing this?

I have now solved it as follows but not sure if this is ok?
`$chat=App::make('chat');
$participants=[1,2];
$conversation=$chat->createConversation($participants);
`

**Comment by musonza** [comment]
@jonaspoelmans You can import the facade as follows:
```
use \Chat;

$participants = [1,2];
$conversation = Chat::createConversation($participants);
```
If you have package discovery disabled you would need to add the facade `Chat` to `config/app.php`

**Comment by jonaspoelmans** [comment]
That works! Thanks for the very quick answer!

**Comment by pshenichniyinfo** [comment]
I have the same problem, the methods above did not help

**Comment by yacinegithub** [comment]
1- When Changing "use Musonza\Chat\Chat" to "use Chat" i get  Class 'Chat' not found
2- When adding the facade Chat to config/app.php i get "Argument 1 passed to Musonza\Chat\Chat::__construct() must be an instance of Musonza\Chat\Services\MessageService, instance of Illuminate\Foundation\Application given, called in /home/tawsse59/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 208"
3- am using L8.X
