### ISSUE TITLE
[Message] read_at should be the participant's read_at

### ISSUE THREAD

**Issue by fokoz** [musonza/chat#110]
`read_at` seems like to be the sender's read time, it is useless because we want to know if the reader has seen or not.

**Comment by musonza** [comment]
Can you share your piece of code rather than saying it’s useless? I can only tell of the issue if I see your implementation.

**Comment by fokoz** [comment]
In the master:

`'mc_message_notification.updated_at as read_at',   `

is quite not usable.

So, I have extended `Message` model from yours:

```
    public function notifications()
    {
        return $this->hasMany(MessageNotification::class);
    }

    public function readParticipants()
    {
        return $this->notifications()->where('is_seen', true);
    }
```
When get messages, it should be used like this:
`Message::withCount('readParticipants as read')`

So we can check read count(if 1:1 chat and read=2, it means that another participant have already read)and show in the client side.

**Comment by musonza** [comment]
Why not use the functions i have in the readme? These tests also have examples https://github.com/musonza/chat/tree/master/tests/Unit

If you write your code that way you also would need to  pass in the $user in your query if you want a different user.
https://github.com/musonza/chat/blob/77bdf9aea7b7d78680b5412c84cf8591be83de62/src/Models/Message.php#L96
