### ISSUE TITLE
Broadcasting can't listen to the MessageWasSent Event

### ISSUE THREAD

**Issue by Jaspur** [musonza/chat#111]
Hi,
Is there a more clear example of how to Broadcasting should be configured?
All messages are pushed correctly to Pusher, but I can't Listen for it. It's returning 403's on /broadcasting/auth. 
@musonza

**Comment by musonza** [comment]
403 sounds like a permission issue and not an issue with package. Can you show the code where you are listening for anyways.

**Comment by Jaspur** [comment]
I fixed the 403, but still not getting the Messages:

```
window.Echo.channel(`private-mc-chat-conversation.1`)
    .listen('MessageWasSent', (e) => {
        console.log(e.update);
    })
```

And this in ```routes/channels.php```:

```
php
Broadcast::channel('private-mc-chat-conversation.{conversationId}', function ($conversationId) {
    return true;
});

Broadcast::channel('private-mc-chat-conversation', function () {
    return true;
});

```

**Comment by musonza** [comment]
You need the fully qualified name for MessageWasSent like `Musonza\Chat\Messages\MessageWasSent` not just `MessageWasSent`
https://github.com/musonza/chat/issues/67

**Comment by Jaspur** [comment]
@musonza doesn't work either:

```
window.Echo.channel(`private-mc-chat-conversation.1`)
    .listen('.Musonza.Chat.Eventing.MessageWasSent', (e) => {
        console.info(e);
    });
// This also not working:
window.Echo.channel(`private-mc-chat-conversation.1`)
    .listen('Musonza\Chat\Messages\MessageWasSent', (e) => {
        console.info(e);
    });
```

**Comment by musonza** [comment]
See https://laravel.com/docs/5.7/broadcasting#namespaces
