### ISSUE TITLE
last_messages gives always the first found mc_message_notification back

### ISSUE THREAD

**Issue by pmochine** [musonza/chat#118]
Hey, first of all, thank you for this beautifully written package! I love how you code!

However, I have found an error that I'm trying to fix with a pull (let's see if I can fix it haha).

To show you my bugs, I have written two easy tests:

	/** @test */
	public function no_inbox_is_loaded_when_messages_is_deleted_by_authenticed_user() 
	{
		$this->deleteMessage(1) //id of 1
	         ->assertStatus(202);

	   	$this->deleteMessage(2) //id of 2
	   	     ->assertStatus(202);

	    $this->inbox() //fetching inbox
	         ->assertJsonCount(0, 'data') //failing, last_message is still shown
	         ->assertStatus(200);
	}

To understand this test. I have a conversation with auth->user() and a receiver with two messages written by the authenticated user. 

I delete two messages with `\Chat::message($message)->for(auth()->user())->delete();` 
(So it is only deleted for the authenticated user)

In inbox() I'm calling (to make it short): ` \Chat::conversations()->for($auth)->get();`

The test should be successfull, because we deleted all of auth messages, so we should not get any last_messages. But it still we get the last_message even though we deleted it.

Now I've come to another test, where the problem exists.

	/** @test */
	public function status_is_seen_is_given_back_correctly() 
	{
		$this->inbox() //inbox of autenticated user
			 ->assertJsonFragment(["is_seen" => "1"]);

		$this->signInAPI($this->data['receiver']);

		$this->inbox()
			 ->assertJsonFragment(["is_seen" => "0"]); //it fails we get it's seen
	}

This test is another simple test. It fetches the inbox of the authenticated user and checks if his written messages are set as seen. (They always are because it's written by the authenticated user).

However, when we signIn as the receiver, we should see the two messages sent by the auth user, as not seen. BUT we get it as seen! 

If I look at the database, `mc_message_notification`is set correctly:

![image](https://user-images.githubusercontent.com/25006691/51377381-0ee52800-1b0b-11e9-9798-d5516a727d01.png)

User 1 is the auth->user() and 4896 is the receiver. The receiver did not see the messages yet.

**Comment by pmochine** [comment]
First small update:

I translated the failed tests from my examples in your `ConversationTest.php`:

    /** @test */
    public function it_returns_last_message_as_null_when_the_very_last_message_was_deleted() 
    {
        $conversation = Chat::createConversation([$this->users[0]->id, $this->users[1]->id]);
        $message = Chat::message('Hello & Bye')->from($this->users[0])->to($conversation)->send();
        Chat::message($message)->for($this->users[0])->delete();

        $conversations = Chat::conversations()->for($this->users[0])->get();
        
        $this->assertNull($conversations, $conversations->get(0)->last_message);
    }

    /** @test */
    public function it_returns_correct_attributes_in_last_message() 
    {
        $conversation = Chat::createConversation([$this->users[0]->id, $this->users[1]->id]);
        Chat::message('Hello')->from($this->users[0])->to($conversation)->send();

        $conversations = Chat::conversations()->for($this->users[0])->get();

        $this->assertTrue(!! $conversations->get(0)->last_message->is_seen);

        $conversations = Chat::conversations()->for($this->users[1])->get();

        $this->assertFalse(!! $conversations->get(0)->last_message->is_seen);

    }

Now it's time to fix it 🗡

**Comment by pmochine** [comment]
I opened a pull request :) 

Please have a look.

**Comment by musonza** [comment]
Thanks for the detailed feedback and your help. I will take a look.

**Comment by pmochine** [comment]
@musonza thank you :)
