### ISSUE TITLE
Private/Public Conversations

### ISSUE THREAD

**Issue by JonathanPort** [musonza/chat#120]
Hi

A client has asked whether we can now have two type of chat rooms.. 😅 So after building the current private chatroom around musonzachat, I now have to make the same but a room that can be publicly accessible. Obviously I want to keep using this library but I need a way to pull conversations based on 'private' column. 

I tried using Eloquents default ->where('private', true) but that doesn't work. Is it possible to add a method in the Chat model to call private convos? Something like this:

$conversations = Chat::conversations()
                             ->for(Auth::user())
                             ->private(true)
                             ->get();

Or in the case of the public chat room browse page:
// Gets all public chat rooms
$conversations = Chat::conversations()
                             ->private(false)
                             ->get();

Also a method when creating conversations to make it private too?

Even better would be a where method so we can query the DB table directly so I can customise as much as I want.

**Comment by musonza** [comment]
Hey, sure i will work on a PR for that this weekend

**Comment by JonathanPort** [comment]
Hey thanks so much!

**Comment by JonathanPort** [comment]
Hey man @musonza , just saw you pushed this to master you legend! Thanks so much for that. Think I mentioned before about helping out around some of your repos, as soon as I have spare time on the weekends, i'll defo give you a shout! Thanks again, much appreciated ❤️

**Comment by musonza** [comment]
No problem. Yes just make sure to republish your config and adjust this value accordingly https://github.com/musonza/chat/blob/71e846f63432e6903d9aceb3f6975e693015e930/config/musonza_chat.php#L23
Otherwise, it will keep the default behavior of classifying conversations of 3 or more people public
