### ISSUE TITLE
Using 'isPrivate(true)' Method with 'getById' method still returns the public model

### ISSUE THREAD

**Issue by JonathanPort** [musonza/chat#122]
Hi thanks again for the work yesterday just one issue I've spotted,

Doing:

$conversations = Chat::conversations()
                             ->for(Auth::user())
                             ->isPrivate()
                             ->get();

only returns the private convos. But doing:

$conversations = Chat::conversations()
                             ->for(Auth::user())
                             ->isPrivate()
                             ->getById($id);

Still returns the convo, private or not.

Is this an easy fix?

**Comment by musonza** [comment]
I don't see the use case when you are already specifying the `id`. If you are already going to do the query why not just check the result if it's private or public?

**Comment by JonathanPort** [comment]
In my case it's when i'm in the private chat room and I go to 'public-chat-room/convo/{id}', that will still show the private room and vice versa for 'private-chat-room'. It won't be a big deal in the controller for me to grab the id, manually find the convo record and abort(404) if not private but having the isPrivate() method on ->getById($id) is really handy. 

Just to clarify, the isPrivate() method exists when using getById but it doesn't work. Just pointing that out. No biggie if it can't be fixed right now.
