### ISSUE TITLE
Added an extra orderBy in getConversationsList to fix a small order issue

### ISSUE THREAD

**Issue by pmochine** [musonza/chat#123]
Hey Tinashe! 

Sorry for creating another small issue, but I opened another pull request for you to see/check.

I had this test issue, that the order of the last_message was not correct.

You can check this with this test:

    /** @test */
    public function it_returns_the_correct_order_of_conversations_when_updated_at_is_duplicated() 
    {
        $auth = $this->users[0];

        $conversation = Chat::createConversation([$auth->id, $this->users[1]->id]);
        Chat::message('Hello-'. $conversation->id)->from($auth)->to($conversation)->send();

        $conversation = Chat::createConversation([$auth->id, $this->users[2]->id]);
        Chat::message('Hello-'. $conversation->id)->from($auth)->to($conversation)->send();

        $conversation = Chat::createConversation([$auth->id, $this->users[3]->id]);
        Chat::message('Hello-'. $conversation->id)->from($auth)->to($conversation)->send();

 
        $conversations = Chat::conversations()->setPaginationParams(['sorting' => 'desc'])->for($auth)->limit(1)->page(1)->get();
        $this->assertEquals('Hello-3', $conversations->items()[0]->last_message->body);

        $conversations = Chat::conversations()->setPaginationParams(['sorting' => 'desc'])->for($auth)->limit(1)->page(2)->get();
        $this->assertEquals('Hello-2', $conversations->items()[0]->last_message->body);

        $conversations = Chat::conversations()->setPaginationParams(['sorting' => 'desc'])->for($auth)->limit(1)->page(3)->get();
        $this->assertEquals('Hello-1', $conversations->items()[0]->last_message->body);
        
    }

When you test this, you will see it is going to fail. That is because updated_at has the same "value". So we need to order by its id to fix it.

Thank you :)

**Comment by musonza** [comment]
No worries, thanks for your help :)

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v3.2.2
