### ISSUE TITLE
Sorting conversations by last message

### ISSUE THREAD

**Issue by zek** [musonza/chat#127]
~~~
Chat::conversations()->for(\App\User::find(1))
    ->limit(20)
    ->page(1)
    ->get();
~~~ 

I am able to get conversation list like this but I need to sort conversations by last sent message.

Is there any proper way to do this?

**Comment by musonza** [comment]
I will look at that. In the meantime you could use the fact that when a message is sent a conversation is updated https://github.com/musonza/chat/blob/03ac9e2a33d3d516483bfca4607083056cd46926/src/Models/Conversation.php#L304

**Comment by zek** [comment]
Yeah I also noticed that it is updated after each message. 

Adding this to the documentation could be useful 

Thanks :)
