### ISSUE TITLE
Facade Not Found

### ISSUE THREAD

**Issue by c-fitzmaurice** [musonza/chat#128]
I installed the package, placed the Alias and ServiceProvider in `config/app.php` and I am getting the following error.

`Class 'Musonza\Chat\Facades\ChatFacade::class' not found`

This is happening in the browser and PHPUnit tests when using a method on the `Chat` facade.

**Comment by Hirbod** [comment]
I have the same issue here, was searching the issues hoping to find a solution. @musonza any thoughts what might be wrong? I followed your demo and your README but I don't know what might have been wrong

**Comment by musonza** [comment]
What version do you have installed?

**Comment by Hirbod** [comment]
@musonza sorry, was about to edit my post. I am using Laravel 5.7 and "musonza/chat": "^3.2",

**Comment by musonza** [comment]
are you using auto discovery or you added 'Chat' => Musonza\Chat\Facades\ChatFacade::class to your `config\app.php`

**Comment by Hirbod** [comment]
I've added 'Chat' => Musonza\Chat\Facades\ChatFacade::class, not sure if I am using auto discovery. I am pretty new into Laravel

**Comment by Hirbod** [comment]
Might be worth noticing that I have initially started with 5.6 and updated to 5.7

**Comment by musonza** [comment]
what exact version is in your `composer-lock`?

**Comment by Hirbod** [comment]
```
 {
            "name": "musonza/chat",
            "version": "v3.2.3",
            "source": {
                "type": "git",
                "url": "https://github.com/musonza/chat.git",
                "reference": "03ac9e2a33d3d516483bfca4607083056cd46926"
            },
```

**Comment by musonza** [comment]
can you comment out  'Chat' => Musonza\Chat\Facades\ChatFacade::class and run `composer require musonza/chat`

**Comment by c-fitzmaurice** [comment]
I can confirm it’s not working via auto discovery or manual install. 

After composer install/dump-auto load it prints the package has been discovered but it’s not registering.

**Comment by Hirbod** [comment]
Done. 

1) Removed line from app.php
2) 

```bash
composer require musonza/chat
Using version ^3.2 for musonza/chat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
```

No change.

```json
{
    "error": {
        "message": "Class 'Musonza\\Chat\\Facades\\ChatFacade::class' not found",
        "status_code": 500
    }
}
```

**Comment by musonza** [comment]
a fix will be pushed in a few mins

**Comment by Hirbod** [comment]
Thank you very much @musonza! Highly appreciated

**Comment by c-fitzmaurice** [comment]
Same, @Hirbod! Really appreciate the quick fix @musonza

**Comment by Hirbod** [comment]
I can confirm, v3.2.4 has fixed the issue! Thank you very much.
