### ISSUE TITLE
How can i setup pusher with your demo?

### ISSUE THREAD

**Issue by bhavin-zwt** [musonza/chat#130]
Hii @musonza 

I have one query regarding your demo example. I have setup in local system and working very well but this is not real time messaging system. This is look like page refresh and normal ajax or vue post request.

So how can i make this demo to real time messaging system. If you have real time message system demo then you can share me.

Please explain if possible then how can convert your demo example to real time messaging system.

Can we add socket type setting to make real time system in your package of chatting? Do you thing about it?

Thanks for demo.

**Comment by musonza** [comment]
You can test this out here https://github.com/musonza/chat-demo/blob/62e39992070b3a63053c43ad4e9a3191cd709d6d/resources/js/components/ChatMessages.vue#L60

**Comment by bhavin-zwt** [comment]
Ohh I have seen that.

But i don't know when i will add that MIX_PUSHER_APP_KEY and MIX_PUSHER_APP_CLUSTER to that file and remove comment of enablePusher function. Then message functionality will be updated by pusher with real time system! OR Do i will update more code to your demo to make real time system with pusher.

I f you all ready done then please inform so i can purchase the Pusher plan and just add those key to you demo code function file.

So can you confirm first then i sure to purchase the plan of pusher.

Thanks for your answer.

**Comment by musonza** [comment]
You can signup for a free pusher account and test

**Comment by bhavin-zwt** [comment]
I have set all app detail in .env file and remove comment from your defined file but nothing happened it is working like before when i have run demo without Pusher.

Can you told what i am missing thing in your demo projact?

**Comment by musonza** [comment]
are you using Laravel Echo
https://github.com/musonza/chat-demo/blob/62e39992070b3a63053c43ad4e9a3191cd709d6d/resources/js/bootstrap.js#L53
If it doesn't work you have to search under laravel echo questions since all the package is doing is fire events. Do you see any events in Pusher dashboard?

**Comment by bhavin-zwt** [comment]
I have removed comment from code for laravel echo code from bootstrap.js file.

But it does not wok. 

I have checked dashboard data for that app in pusher. It show like below.

![pusher_dashboard](https://user-images.githubusercontent.com/45998022/54128386-f837bf00-4431-11e9-91b6-5421ff937afa.jpg)

**Comment by bhavin-zwt** [comment]
Do you have live demo url project? I wan to test and see how this worked exactly from front side how the response is going on so i can see how this is working exactly according your demo and pusher.

**Comment by AndTras** [comment]
@bhavin-zwt  Did you make it work?

**Comment by bhavin-zwt** [comment]
@AndTras  Yes, I have made demo using the pusher.
