### ISSUE TITLE
Class name must be a valid object or a string error on createConversation in laravel 5.8

### ISSUE THREAD

**Issue by Digital4design** [musonza/chat#133]
On creation of conversation, I am getting error- Class name must be a valid object or string.
It would be highly appreciated if anyone can help with it.

$participants = [Auth::user()->id, $this->admin->id];
$conversation = Chat::createConversation($participants);

**Comment by musonza** [comment]
Can you provide more info on what's in the error logs. Which Class name is being said in this case?

**Comment by Digital4design** [comment]
Solved it yesterday. Thanks.
