### ISSUE TITLE
Hardcoded constraint to 'id' on 'users' table

### ISSUE THREAD

**Issue by goranjviv** [musonza/chat#134]
I see a potentially big issue with this - even though you allowed us to use a model other than `App\User`, in migrations you're supposing that conversations will be between entities stored in `users` table, which might not be the case at all. All sorts of integrity problems could arise with this approach.

Should be changed so that you use the table for the model set in the config.

**Comment by musonza** [comment]
Yes thanks, feel free to make a PR. Otherwise i can address as soon as i get a chance.

**Comment by goranjviv** [comment]
Will make a pr with addressing this issue during the weekend, I hope.

**Comment by musonza** [comment]
fyi - i'm working on this https://github.com/musonza/chat/pull/135

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v3.3.0
