### ISSUE TITLE
getMessages() returns only 25 messages but I need all

### ISSUE THREAD

**Issue by miras1726** [musonza/chat#137]
Hi, great work

But here I faced an issue, when I try to get all messages for user 
`Chat::conversation($conversation)->setUser($user)->getMessages()`
I get only 25 of them.

In your ConversationService class getMessages method there is no way to pass any paginate params. I don't know is it bug or not but is there are a way to fetch all the messages for user? 
Thank you

**Comment by musonza** [comment]
See this https://github.com/musonza/chat#pagination and let me know if you have issues

**Comment by miras1726** [comment]
Oh yes sorry I got it. But should I always specify 'perPage' param if I want more than 25 messages or is there a way to fetch all?

**Comment by musonza** [comment]
Yes you have to specify. Here are the defaults
https://github.com/musonza/chat/blob/ce4e6f4aa46301a304d666fe5c4ef04b91e3825c/src/Traits/Paginates.php#L7-L12
No way to fetch all because that could be a lot of messages but if you have a limit for user messages then just specify the expected size.

**Comment by miras1726** [comment]
Ok thank you

**Comment by AEK-BKF** [comment]
Hi @gomer1726,
Please, how did you resolve the problem ? I have the same issue, I cannot get conversation messages paginated !
Thanks

**Comment by gomer1726** [comment]
@AEK-BKF Hi. Did you solve your problem? Let me know if not

**Comment by VivaJosh** [comment]
to paginate messages 

```php
Chat::conversation($conversation)
                ->setParticipant(auth()->user())
                ->setPaginationParams([
                    'page' => 1,
                    'perPage' => 50, // your max
                    'sorting' => "desc", // "asc"
                ])
                ->getMessages()
                ```
                this might help someone too
