### ISSUE TITLE
User Message relationship

### ISSUE THREAD

**Issue by quantumwebco** [musonza/chat#140]
When getting a conversation and looping through messages there is no relationship between the message and the user so e.g. ```$message->user->name``` does not work. 

Is there a relationship and how do I access it?

**Comment by musonza** [comment]
Hey, here is the relationship
https://github.com/musonza/chat/blob/0ecc3f3fb5c3ccb8f10993e322cbf5990d372734/src/Models/Message.php#L33-L36

So do something like 

```php
$message->sender->name
```

**Comment by quantumwebco** [comment]
Oh sorry yeah I already trawled through the models and found it was sender. Thanks though!!
