### ISSUE TITLE
Migration error for constraints

### ISSUE THREAD

**Issue by LastxTemplar** [musonza/chat#147]
**Describe the bug**
My environment runs `Laravel v5.8.11`
Running the migration errors out because it cannot create the foreign key constraints to the users table

**To Reproduce**
1.  Follow the instructions in the Readme
2.  Run `php artisan migrate`
3.  You will see `SQL error 1215` about not being able to create foreign key constraints

**Expected behavior**
It should migrate without errors

**Solution**
This happens because the `id` column on the `users` table is of type `bigIncrements`. 

The `user_id` columns in these tables: `mc_messages`, `mc_conversation_user` and `mc_message_notification` are of type `integer`, they should be `bigInteger` instead.

The solution is to find all instances of this line in the `create_chat_tables.php migration`:
`$table->integer('user_id')->unsigned();`
and change them to this:
`$table->bigInteger('user_id')->unsigned();`

**Comment by nereauweb** [comment]
Done it, it solved the reported error, but then I got a new one: SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (SQL: alter table `mc_conversation_user` add primary key `mc_conversation_user_user_id_conversation_id_primary`(`user_id`, `conversation_id`))

It happens on the third table created (mc_conversation_user). I'm trying to find a solution for this, but with no luck. Any suggestion?

**Comment by nereauweb** [comment]
got it to complete commenting out $table->primary(['user_id', 'conversation_id']); :

 ```
Schema::create('mc_conversation_user', function (Blueprint $table) {
                $table->bigIncrements('user_id')->unsigned();
                $table->bigInteger('conversation_id')->unsigned();
                //$table->primary(['user_id', 'conversation_id']);
                $table->timestamps();

                $table->foreign('conversation_id')
                    ->references('id')
					->on('mc_conversations')
                    ->onDelete('cascade');
				
                $table->foreign('user_id')
                    ->references($this->userModelPrimaryKey)
                    ->on($this->userModelTable)
                    ->onDelete('cascade');
            });
```

Still not sure if it's going to work correctly. I think migration needs a review...

**Comment by nereauweb** [comment]
I think to have solved the last error: conceptually, we don't need autoincrement for user_id in mc_conversation_user, so it should be `$table->bigInteger('user_id')->unsigned()`, or `$table->bigIncrements('user_id')->unsignedBigIntegers()` (no bigIncrements).
Without that, i could de-comment the `$table->primary(['user_id', 'conversation_id']);` line with no further errors.

**Comment by musonza** [comment]
@nereauweb good catch, that was unintentional copy and paste. I will fix that now

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v3.4.1
