### ISSUE TITLE
when create massage  Class name must be a valid object or a string

### ISSUE THREAD

**Issue by MuhamedMohsen** [musonza/chat#148]
**Describe the bug**
**Class name must be a valid object or a string**

**To Reproduce**
 ```
public function store()
    {
        $participants = [auth()->user()->id];
        $conversation = Chat::createConversation($participants);
        dd($conversation);
        return response($conversation);
    }
```

**Screenshots**

**Comment by musonza** [comment]
You mean the class Chat? Did you import it

**Comment by MuhamedMohsen** [comment]
[](url)
![image](https://user-images.githubusercontent.com/28537814/61470198-ee463f80-a980-11e9-8977-b58f19de25c5.png)

**Comment by MuhamedMohsen** [comment]
Need Solve error

**Comment by Baghdasarov** [comment]
@MuhamedMohsen add this line to config/musonza_chat.php
'sent_message_event' => 'Musonza\Chat\Eventing\MessageWasSent',

It must be have something like this. http://i.prntscr.com/8qwVXKFfSkWfQ35_2JB-5Q.png

Hope it help you.
