### ISSUE TITLE
Adding update last conversation message field

### ISSUE THREAD

**Issue by devWaleed** [musonza/chat#15]
Hey, can you add a new field in conversations table for last message date ? It would be much quicker to sort conversations based on that.

**Comment by tolgatasci** [comment]
Messages Table already have


 ```
Schema::create('messages', function (Blueprint $table) {
            $table->increments('id');
            $table->text('body');
            $table->integer('conversation_id')->unsigned();
            $table->integer('user_id')->unsigned();
            $table->string('type')->default('text');
            $table->timestamps(); // Adding DATE
            $table->foreign('user_id')
                ->references('id')
                ->on('users');
            $table->foreign('conversation_id')
                ->references('id')
                ->on('conversations');
        });
```


$table->timestamps();  already have

**Comment by devWaleed** [comment]
We can sort messages this way but not the conversations. Look at this piece of code:

        $user = Auth::user();

        $_convs = $user->conversations;
        $convs_ids = $_convs->pluck('conversation_id');

        $convs = ConversationUser::
            whereIn('conversation_id', $convs_ids)
            ->where('user_id', '!=', $user->id)
            ->with('messages')
            ->with('user')
            ->get();

This gives me a list of ConversationUser which are mostly the other user in the conversation. I have strictly 1 on 1 conversations i.e two users only. So this way I can easily fetch the other user and display them like Messenger. But I can't sort them this way since relational sorting is not possible. 

Do you think there is a better way of doing this? Can you improve it?

**Comment by tolgatasci** [comment]
i type
https://github.com/musonza/chat/issues/14

I think you are looking for something like that.

2 user's profile

**Comment by devWaleed** [comment]
$recent_message = $user->conversation->messages()->orderBy('id', 'desc')->first()->toArray();

Can you provide this relation in Users model?

**Comment by devWaleed** [comment]
Well never mind, I solved it another way. I could have created those joins myself but the problem is I don't like joins since they don't support Eloquent relations. I like to query through relations.

So I am using my current piece of code for retrieving each 'other user' of my current user's conversation and also all messages of that conversation same what you did but using Eloquent:

        $convs = ConversationUser::
            whereIn('conversation_id', $convs_ids)
            ->where('user_id', '!=', $user->id)
            ->with('messages')
            ->with('user')
            ->get();

Now sorting was the issue right? Well, I used JS to sort the list of users as well as messageContainer like this:

Printing User's list:

		<ul id="user-list-ul" class="list-group">
			@foreach( $conversations as $key => $value )
			<li data-listing-val="{{ $value->messages->last()->created_at->timestamp }}" 
				class="tab-li userContainer list-group-item">
				<a class="user-name" href="#c_{{ $value->conversation_id }}" data-toggle="tab">			
					{{ $value->user->name }}
				</a>
			</li>
			@endforeach
		</ul>

Printing messages:

@foreach( $conversations as $key => $value )
		<div  data-listing-val="{{ $value->messages->last()->created_at->timestamp }}" id="c_{{ $value->conversation_id }}" class="messageContainer messages-container tab-pane fade in">
			<div class="messages-area">
				@foreach ( $value->messages as $key2 => $message )
				<div class="message">
					<div class="row">
						@if ( Auth::user()->id == $message->user_id )
                                                // ignore this piece of code :laughing: 
						<?php $class = ''; ?>
						@else
						<?php $class = 'pull-right'; ?>
						@endif

						<div class="col-md-1 {{ $class }}">
							<img class="img-responsive img-circle" src="{{ url('/') . Storage::url($message->senderAvatar()) }}">
						</div>
						<div class="col-md-11">
							<div class="{{ $class }}">
								{{ $message->body }}
							</div>
						</div>
					</div>
				</div>
				@endforeach			
			</div>
			<div class="message-box">
				{{ Form::open() }}
				{{ Form::hidden('uni_id', $value->user_id) }}
				{{ Form::textarea('message', null, [ 'class' => 'form-control', 'placeholder' => 'Type a reply' ] ) }}
				{{ Form::submit('SEND', ['class' => 'btn btn-info send_btn']) }}
				{{ Form::close() }}
			</div>
		</div>
		@endforeach

and then simply sorting it using JS also making first li and tabcontent to be active:

	var divList = $(".userContainer");
	divList.sort(function(a, b){
		return $(b).data("listing-val") - $(a).data("listing-val")
	});
	$("#user-list-ul").html(divList);

	var divList = $(".messageContainer");
	divList.sort(function(a, b){
		return $(b).data("listing-val") - $(a).data("listing-val")
	});
	$("#messagesContainer").html(divList);

	$(document).ready(function(){
		$('.messages-area').scrollTop($('.messages-area')[0].scrollHeight);
		$('.userContainer:first-child').addClass('active');
		$('.messageContainer:first-child').addClass('active');
	});

Though scrolling code is not working but I'll fix it later.

**Comment by musonza** [comment]
This will be in a new version that i will release soon.
