### ISSUE TITLE
Add ability for custom tables names

### ISSUE THREAD

**Issue by kirillarutyunov** [musonza/chat#155]
I can publish migrations and change tables names, that's why I need ability to set new tables names in config file. Now there are a lot of places in models where tables names used directly, not from config or tableName() func.

What do you think about it?

**Comment by musonza** [comment]
Is there any reason you want to change the names since the names are already prefixed to avoid conflicts

**Comment by kirillarutyunov** [comment]
> Is there any reason you want to change the names since the names are already prefixed to avoid conflicts

Codestyle and table-name convention inside our project. This is the only reason in my situation.

**Comment by musonza** [comment]
Closing this time as it results in a  lot of breaking changes
