### ISSUE TITLE
Syntax error, access voilation for user Conversations

### ISSUE THREAD

**Issue by devWaleed** [musonza/chat#16]
I did this piece of code 

```
$user = Auth::user();
$mesages = Chat::conversations($user->id);
```

and it gave me this error:

`SQLSTATE[42000]: Syntax error or access violation: 1055 'mydb.messages.id' isn't in GROUP BY (SQL: select `messages`.*, `messages`.`id` as `message_id`, `conversation_user`.* from `conversation_user` inner join `messages` on `messages`.`conversation_id` = `conversation_user`.`conversation_id` where `conversation_user`.`user_id` = 19 group by `messages`.`conversation_id` order by `messages`.`id` desc)`

My user is authenticated and I have some messages/conversations in table as well.

**Comment by tolgatasci** [comment]
https://stackoverflow.com/questions/40917189/laravel-syntax-error-or-access-violation-1055-error
