### ISSUE TITLE
Queting: How to use  Non-default database

### ISSUE THREAD

**Issue by fujiwaraizuho** [musonza/chat#160]
Hi. 
Thank you for a very good library!

In my app, I have a default database and Chat database.

Looking at the code, it seems that a database error will occur in the model file even if the migration file is changed.

How do I handle that?

**Comment by musonza** [comment]
I can add the ability to specify a database connection

**Comment by fujiwaraizuho** [comment]
Very good news!!!
When will it be?

**Comment by fujiwaraizuho** [comment]
@musonza
When will it be completed?
