### ISSUE TITLE
Postgresql: distinct error after upgrading to Laravel 6.0

### ISSUE THREAD

**Issue by affektde** [musonza/chat#164]
**Describe the bug**
I try to get all conversation from a user with `$conversations = Chat::conversations()->setUser($customer)->setPaginationParams([
      'perPage' => 1000,
    ])->get()->getCollection();`

Postgres throws an exception of:

```sql
SQLSTATE[42P10]: Invalid column reference: 7 ERROR:  SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: select distinct on (\"mc_conversations\".\"id\") \"mc_conversatio...
^ (SQL: select distinct on (\"mc_conversations\".\"id\") \"mc_conversations\".* from \"mc_conversations\" inner join \"mc_conversation_user\" on \"mc_conversation_user\".\"conversation_id\" = \"mc_conversations\".\"id\" where \"mc_conversation_user\".\"user_id\" = 1 order by \"mc_conversations\".\"updated_at\" desc, \"mc_conversations\".\"id\" desc limit 25 offset 0)
```

Only thing that I've changed on my system was upgrading to Laravel 6.0.

**To Reproduce**
1.  install latest version 3.5.0
2.  install Laravel latest version 6.0.4
3.  try to get a list of all conversations from a user

**Expected behavior**
No Postgresql errors thrown.

**Additional context**
My whole `mc_conversations` table was built with latest Laravel 5.6 version and latest `musonza/chat` version. I don't think it's an issue with the data. The search on the Internet revealed that Postgres might require subqueries for distinct here. And Laravel had made changes here to my knowledge.

I'm still looking for the trigger, and write back if I find anything.

**Comment by affektde** [comment]
Ok, if you add `mc_conversations.id` as `orderBy` then it works.

```php
        return $paginator
            ->orderBy('mc_conversations.id', 'DESC')
            ->orderBy('mc_conversations.updated_at', 'DESC')
            ->distinct('mc_conversations.id')
            ->paginate($perPage, ['mc_conversations.*'], $pageName, $page);
```

I will write a pr.

**Comment by affektde** [comment]
I am sorry, my composer vendor did not update correctly. I see that this was just committed as a change.

**Comment by affektde** [comment]
Could it be that the order of `orderBy` is important after all? I have errors mentioned above in the issue back in my system. When exchanging the `orderBy` lines it works again.

```php
        return $paginator
            ->orderBy('mc_conversations.id', 'DESC')
            ->orderBy('mc_conversations.updated_at', 'DESC')
            ->distinct('mc_conversations.id')
            ->paginate($perPage, ['mc_conversations.*'], $pageName, $page);
```

I am still on postgresql 11.5. Is it caused by an update of latest postgresql?

**Comment by hellodit** [comment]
it's already fixed? i found same error on version 6 using Postgres latest

**Comment by hellodit** [comment]
it's 5 years issue and not fixed yet
