### ISSUE TITLE
Not installable on Laravel 6.4.0

### ISSUE THREAD

**Issue by Hirbod** [musonza/chat#171]
This package is currently only installable on 6.0. I don't see any breaking changes with 6.4.0. You might also want to add ^6.0 instead of ~6.0 ?

@musonza

**Comment by musonza** [comment]
hi, could you make a PR and i will merge. Thanks

**Comment by musonza** [comment]
https://github.com/musonza/chat/pull/175

**Comment by Hirbod** [comment]
Thank you very much. Was about to push a PR but you also did some more adjustments then I would've. Works great so far
