### ISSUE TITLE
Add a sponsor button to your repo

### ISSUE THREAD

**Issue by Hirbod** [musonza/chat#181]
Hi,

as a developer (and open source developer myself) I know how much work and time consuming a free project can be. Please set up your sponsoring button, so we can leave some beer and coffee for you :)

https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

**Comment by Hirbod** [comment]
P.S: I would recommend you to set up a custom url linking to something like https://www.paypal.me/abcdefg

**Comment by musonza** [comment]
Thanks, will check that out

**Comment by musonza** [comment]
https://github.com/musonza/chat/pull/214
