### ISSUE TITLE
Limit user data in "sender"

### ISSUE THREAD

**Issue by Hirbod** [musonza/chat#189]
Hi,

`last_message` contains the `sender`. It contains all the database fields. Can we somehow limit the fields which should be returned?

**Comment by musonza** [comment]
https://github.com/musonza/chat/pull/191

**Comment by Hirbod** [comment]
Very nice, thank you. Could we also limit those fields for the user?

**Comment by Hirbod** [comment]
I just tested this, it works great, but I will open up another issue regarding the users array
