### ISSUE TITLE
Limit data in "users"

### ISSUE THREAD

**Issue by Hirbod** [musonza/chat#204]
Hi @musonza, 

first of all: thanks for the quick update on #189.
It works great. But when I send a message for example, I get a big response which has `conversation` and inside of this, I get the users array, with all connected users to this conversation. All data fields are exposed as well. Would love to limit those too. Thanks.

**Comment by musonza** [comment]
hi, it might be worth using transformers for your responses so you have more control of what's returned. Thoughts?

**Comment by Hirbod** [comment]
Yeah, I could also parse the result before returning it..

**Comment by Hirbod** [comment]
Using transformers looks like a good idea, but the response isn’t a single user object, it’s a collection of everything. How can I transform the user collection inside of it? Do I have to iterate through, transform it and append it back to my return?

**Comment by musonza** [comment]
@Hirbod yes you can certainly use transformers for collections and multiple objects
This example includes participants in addition to the conversation
https://github.com/musonza/chat-demo/blob/280017f7aef1eb739a5fe6ecc7f206c36b3533a2/app/Transformers/ConversationTransformer.php#L25

**Other examples**
https://github.com/musonza/chat-demo/tree/master/app/Transformers

A survey form that has questions
https://github.com/musonza/laravel-forms/blob/303abc400bd7b6558b59f63eb5ffc862899c40a7/src/Transformers/FormTransformer.php#L31

**Collection Response examples**
https://github.com/musonza/laravel-forms/blob/303abc400bd7b6558b59f63eb5ffc862899c40a7/src/Http/Controllers/FormController.php#L42
https://github.com/musonza/chat/blob/814a7b58c2991eb68e0bde2c99f1d1a8c0e79d7e/src/Http/Controllers/ConversationController.php#L46-L49

**Single Resource response**
https://github.com/musonza/laravel-forms/blob/303abc400bd7b6558b59f63eb5ffc862899c40a7/src/Http/Controllers/FormController.php#L55
https://github.com/musonza/chat/blob/814a7b58c2991eb68e0bde2c99f1d1a8c0e79d7e/src/Http/Controllers/ConversationController.php#L35


Let me know if this helps

**Comment by musonza** [comment]
Closing as there is a way to limit with transformers provided by the package controllers and also can extend the base transformer if calling the functions directly.
