### ISSUE TITLE
last_message is gone

### ISSUE THREAD

**Issue by Hirbod** [musonza/chat#207]
Hi @musonza,

I just updated to 4.0 - unfortunately it broke everything I worked for. I migrated everything (and there was no migration script as you said) - but anyway, I'm 99% back and I like the whole new approach of this package. Thanks for your hard work.

But where is "last_message"? I can't build my Messenger-Inbox without it. Do I have to grab it explicitly?

**Comment by musonza** [comment]
@Hirbod i would like to work with you on resolving this. Can you add me on discord `tinashe#3295` ? I'm at work right now so i don't have time to take a look

**Comment by Hirbod** [comment]
@musonza I've added you

**Comment by Hirbod** [comment]
can be closed, was because I used the model to retrieve the conversation
