### ISSUE TITLE
DirectMessagingExistsException is thrown, still creates a conversation

### ISSUE THREAD

**Issue by Hirbod** [musonza/chat#208]
v4:
 DirectMessagingExistsException is thrown, still creates a conversation

**Comment by musonza** [comment]
We can create a direct message after the effect so that's why. I have added an option to specify intent to create direct message before conversation creation
https://github.com/musonza/chat/releases/tag/4.0.1

**Comment by Hirbod** [comment]
@musonza I've updated the package and specified the intent, but now, it recreates conversations over and over again, even if there is already one. Is this what you want? Because usally, they shouldn't be more then one 1:1 Chat between to users, no matter who initiated the request.

If you want to keep it this way, give me a shout please, so I will make some checks before myself.

**Comment by musonza** [comment]
can you test with https://github.com/musonza/chat/releases/tag/4.0.3

**Comment by Hirbod** [comment]
Its semi-fixed @musonza 

```php
        $participants = [$request->user(), User::find(53)];
        $conversation = Chat::makeDirect()->createConversation($participants);
```

creates a conversation, and

```
        $participants = [$request->user(), User::find(39)];
        $conversation = Chat::makeDirect()->createConversation($participants);
```

Where 39 is my ID and 53 is the recipients id. Those are the same user-ids but the initiator is someone else. It should not recreate another conversation, it should return the existing one. (if there is any)

**Comment by Hirbod** [comment]
And another interesting bug came with this. Those 2 requests created conversation 74 and 75.
If I send the message to 74 now, its fine, but if I send it to 75 (which exists but shouldn't), I'll get

```
  "message": "Argument 3 passed to Musonza\\Chat\\Models\\Message::send() must be an instance of Musonza\\Chat\\Models\\Participation, null given, called in /home/vagrant/code/vendor/musonza/chat/src/Messages/SendMessageCommandHandler.php on line 33",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/vagrant/code/vendor/musonza/chat/src/Models/Message.php",
```

**Comment by Hirbod** [comment]
And the Exception is till thrown
"exception": "Musonza\\Chat\\Exceptions\\DirectMessagingExistsException",
