### ISSUE TITLE
How to get all conversations of the Authenticated user?

### ISSUE THREAD

**Issue by mrkalmdn** [musonza/chat#23]

**Comment by musonza** [comment]
@mrkalmdn https://github.com/musonza/chat#get-recent-messages

` Chat::conversations()->for($user)->limit(25)->page(1)->get();`

This actually returns the conversations list with the latest message in each conversation.

Does that help?

**Comment by mrkalmdn** [comment]
Hi @musonza,

Tried it. But I'm getting this error.
```sql
SQLSTATE[42S22]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'data->message_id'. (SQL: select [notifications].*, [mc_messages].* from [mc_messages] inner join [notifications] on [notifications].[data->message_id] = [mc_messages].[id] where [mc_messages].[conversation_id] in (1) order by [mc_messages].[id] desc)
```

**Comment by musonza** [comment]
@mrkalmdn Looks like you are using MSSQL. I haven't used MSSQL so i'm not sure about the json column support.

**Comment by mrkalmdn** [comment]
I think my SQL Server doesn't support json column. Thanks anyway.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by musonza** [comment]
You can use the previous version of the package if you want

**Comment by mrkalmdn** [comment]
Will do. Thanks!
