### ISSUE TITLE
Nothing to migrate

### ISSUE THREAD

**Issue by shraddha-islaniya** [musonza/chat#24]
I did follow your steps but my migration and config files didn't create in folder.

**Comment by musonza** [comment]
So nothing happenes when you run 'php artisan vendor:publish' ? What version of laravel are you using?

**Comment by shraddha-islaniya** [comment]
I'm using laravel 5.4.33

**Comment by shraddha-islaniya** [comment]
Oh! I didn't notice that it's only for 5.3. What should I do now?

**Comment by musonza** [comment]
no it should work with laravel 5.4.x. It doesn't work for less than 5.3
