### ISSUE TITLE
Unable to create conversation !

### ISSUE THREAD

**Issue by AEK-BKF** [musonza/chat#249]
I've just installed the package on L6.2.
I tried to create new conversation in order to send a message, I get this error :
` Argument 1 passed to Musonza\Chat\Chat::createConversation() must be of the type array `

Here my simple code:
```
$receivers = User::find($request->receivers);
$conversation = Chat::createConversation($receivers);
$message = Chat::message($request->content)
                    ->from(auth()->user())
                    ->to($conversation)
                    ->send();
```
`$request->receivers` is an input which contain an array of users IDs.

What's wrong ?

**Comment by musonza** [comment]
is `$request->receivers` an array? Can you show the sample input?

**Comment by AEK-BKF** [comment]
I fixed it, thanks.
