### ISSUE TITLE
Create a public conversation without specifying models

### ISSUE THREAD

**Issue by Julien-R44** [musonza/chat#259]
Hello, 

Is there a way to create a public conversation without specifying models ? I don't understand why we are forced to provide models. 
In my application, we have private message system and also public channels where everyone can talk. 

```
        $channels = collect(['Public channel', 'public channel 2']);
        $channels->each(function ($channel) {
            $conversation = Chat::createConversation(User::all()->all())->makePrivate(false);
            $conversation->update(['data' => ['title' => $channel]]);
        });
```

Here is how I am creating public channels actually ( in a seeder ). The first issue I see with this is it's the number of rows created in the chat_participation pivot table ( number of channels * messageable models ). Second issue, everytime a user is registering, we need to add him to the conversation. 
There are not really issues but I don't understand why we need this
otherwise, thanks you for the lib it's really time-saver !

**Comment by musonza** [comment]
Hello, currently there is isn’t but it’s possible to add that functionality but I’m not sure when I can get time to work on that yet. That’s a good point and if you have time before I get to it you can send a PR
