### ISSUE TITLE
musonza send message issue

### ISSUE THREAD

**Issue by guptanand** [musonza/chat#260]
Hi sir

i am beginner and i am install this plugin step by step. but creating message function "createConversation" but this function return required fields. i am searching in google but not any find solution. 

Any one help me step by step .

**Comment by musonza** [comment]
Can you show a screenshot? I’m not sure I understand you issue

**Comment by guptanand** [comment]
![musonza1](https://user-images.githubusercontent.com/67232716/92329218-aeaa4d80-f083-11ea-8fbf-72f689707a34.png)
![musonza2](https://user-images.githubusercontent.com/67232716/92329223-b23dd480-f083-11ea-92fb-738dd8997447.png)

**Comment by musonza** [comment]
You need to pass in a model as the error suggests. See Readme https://github.com/musonza/chat/blob/master/README.md also an example app https://github.com/musonza/chat-demo
```php

$userModel = Auth::user();
$message = Chat::message('Hello')
    ->from($userModel)
    ->to($conversationId)
    ->send();

```

**Comment by guptanand** [comment]
thanxs sir

but return this issue

"message": "Argument 1 passed to
Musonza\\Chat\\Services\\MessageService::to() must be an instance of
Illuminate\\Database\\Eloquent\\Model, string given, called in
E:\\Develpment\\xampp\\htdocs\\chandigarh\\dating\\app\\Http\\Controllers\\Api\\MessageController.php
on line 22",

My url is  http://localhost//abc/public/api/friend/send-message/27

**Comment by musonza** [comment]
You also need to pass the conversation model use `Chat::conversations()->getById($id)` to get the conversation and pass that in the `to` function. The readme has all that info https://github.com/musonza/chat/blob/master/README.md#send-a-text-message

**Comment by guptanand** [comment]
Sir, this is First message and my all chat table empty so
Chat::conversations()->getById($id) return null with error
 "message": "Argument 1 passed to
Musonza\\Chat\\Services\\MessageService::to() must be an instance of
Illuminate\\Database\\Eloquent\\Model, null given, called in
E:\\Develpment\\xampp\\htdocs\\chandigarh\\dating\\app\\Http\\Controllers\\Api\\MessageController.php
on line 24",

**Comment by musonza** [comment]
Yes but `Chat::conversations()->getById($conversationId)` shouldn't return null if you have a conversation created

**Comment by guptanand** [comment]
No Sir, I am not created any conversation. my all table is empty and i am
try to create first message send to user.

$userModel = Auth::user();
$conversation = Chat::conversations()->getById($conversationId);

$message = Chat::message('Hello')
    ->from($userModel)
    ->to($conversation)
    ->send();

My all chat tables is empty. i will try my first message sending.

Error message :- "message": "Argument 1 passed to
Musonza\\Chat\\Services\\MessageService::to() must be an instance of
Illuminate\\Database\\Eloquent\\Model, null given, called in
E:\\Develpment\\xampp\\htdocs\\chandigarh\\dating\\app\\Http\\Controllers\\Api\\MessageController.php
on line 24",

**Comment by musonza** [comment]
if you do `dd($conversation)` what do you get? Make sure you get a conversation returned there first

**Comment by guptanand** [comment]
dd($conversation) is return me null.

If you do not have a problm, you can access my computer on share and help
me.

**Comment by musonza** [comment]
Add me on Discord `tinashe#3295`

**Comment by guptanand** [comment]
thanxs and sure sir

**Comment by guptanand** [comment]
no user found
My id or link
 https://discord.gg/gsqg3S

**Comment by guptanand** [comment]
guptanand#1593

**Comment by guptanand** [comment]
now i am send you request please connected .

**Comment by guptanand** [comment]
[image: image.png]

Yesterday function not any change and today i will try new conersion with
new id but this return again error, why sir.....hmm
