### ISSUE TITLE
Laravel 8.0 Support

### ISSUE THREAD

**Issue by mehranabi** [musonza/chat#262]
Currently, I cannot install `musonza/chat` in my Laravel 8 project.
Any plan to add support for Laravel 8?
I would be happy to help.

**Comment by musonza** [comment]
Yes, if you can make a PR that would be great. Thanks

**Comment by mehranabi** [comment]
Hey @musonza .
Just created a Pull Request: https://github.com/musonza/chat/pull/263

**Comment by musonza** [comment]
Thank you

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v4.5.0
