### ISSUE TITLE
Additional field in chat_message model

### ISSUE THREAD

**Issue by ali4zimi** [musonza/chat#281]
I am designing my app and using this chat. Everything works well but I need one more field in the message table. For example, take a look at my screenshot below:
![Screen Shot 2021-05-05 at 12 00 48 PM](https://user-images.githubusercontent.com/13467999/117109227-9406b080-ad99-11eb-8776-845b21897581.png)

I want to add more details about this message. I can only set what the message type is. I need more details like post_link, post_id, post_image, post_title and etc. The situation differs, so we can't add all these fields to the message table. Therefore, I think it is good to add a field called 'data' in the message table. The same in the 'notification' table of Laravel which stores data as JSON.

Thanks

**Comment by musonza** [comment]
Hello, feel free to make a PR that adds `data` column like we have for the conversation table. Thanks

**Comment by ali4zimi** [comment]
closed by #290
