### ISSUE TITLE
How I can start conversation with oneself but before that check if there already conversation exists?

### ISSUE THREAD

**Issue by siarheipashkevich** [musonza/chat#29]
Could you please explain how I can start conversation with oneself with existing structure of the table (but before that check if there is already conversation with oneself)? Also before starting conversation with oneself I have already other conversations.

**Comment by musonza** [comment]
You can use this to check if two users have already started a conversation:
https://github.com/musonza/chat#get-a-conversation-between-two-users
```
$conversation = Chat::getConversationBetween($user1, $user2);

if($conversation){
   //Send message to existing conversation
   //https://github.com/musonza/chat#send-a-text-message
}else{
   //Start a conversation
  //https://github.com/musonza/chat#creating-a-conversation
}
```

**Comment by ufeg02** [comment]
Is it also possible to check if a conversation with multiple users already exists?

**Comment by musonza** [comment]
$conversation is an Eloquent model so you can pretty much do anything you do with Eloquent Models

So let's say we have found our $conversation

```
$participants = $conversation->users();
```

Or get the count

```
$participantsCount = $conversation->users->count();
```

**Comment by ufeg02** [comment]
What's the most efficient approach to check if a conversation exists between 4 users?

**Comment by musonza** [comment]
There are a few ways you could do this. Here is one:
I will make an update to the package and add something like this but you can use this in the meantime.
```
$userIds = [2,3,5,7];  //these are your four users

function getCommonConversations($userIds){
	$conversations = Musonza\Chat\Conversations\Conversation::withCount(['users' => function ($query) use($userIds){
	    $query->whereIn('id', $userIds);
	}])->get()->filter(function ($conversation, $key) use($userIds) {
	    return $conversation->users_count == count($userIds);
	});

	return $conversations;
}
```

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v2.0.2

See 
https://github.com/musonza/chat#get-common-conversations-among-users

**Comment by Mu9tafa-Online** [comment]
@musonza  How to check if conversation exists between two users on the latest versions (**v4.4.0**) ??
