### ISSUE TITLE
Error Call to undefined method Musonza\Chat\Services\MessageService::data() 

### ISSUE THREAD

**Issue by samehdoush** [musonza/chat#293]
**Describe the bug**
Error Call to undefined method Musonza\Chat\Services\MessageService::data()  When send message with data

**To Reproduce**
1.  $message = Chat::message('Attachment 1')
		->type('attachment')
		->data(['file_name' => 'post_image.jpg', 'file_url' => 'http://example.com/post_img.jpg'])
		->from($model)
		->to($conversation)
		->send();
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/48515888/150559778-f4ff1f00-fd3c-4b7d-88c3-756c99e99e62.png)

**Comment by musonza** [comment]
Hey, you need to have this version installed https://github.com/musonza/chat/releases/tag/v5.0.0
