### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by ibkhall** [musonza/chat#299]

**Comment by Forsakenrox** [comment]
realy necessary

**Comment by samehdoush** [comment]
realy necessary

**Comment by JordivdB** [comment]
Any updates on this?

**Comment by tsachi** [comment]
?

**Comment by hamidafghan** [comment]
#298 @musonza Any plan to merge this PR?

**Comment by stevebrainng** [comment]
No plan to add support for Laravel version 9?

**Comment by musonza** [comment]
Just merged and will created a release

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v6.0.0

**Comment by hamidafghan** [comment]
Thank you @musonza
