### ISSUE TITLE
Fix the order for php artisan migrate

### ISSUE THREAD

**Issue by yazirrizki** [musonza/chat#3]
I dont know, but I got errors when I try to migrate table.
so I fix the order, and voila. Its work.

Maybe if you want to help me, you can share the demo/example from this package?
Btw you are awesome, this package is so nice

**Comment by musonza** [comment]
What did the error message say and what do you mean by the order. Thanks

**Comment by yazirrizki** [comment]
sorry, I am forgot to screenshot, something about foreign key etc

**Comment by yazirrizki** [comment]
Can u provide the example?

**Comment by musonza** [comment]
I don't have an example at hand. What exactly do you need from the example. The **readme** should be enough to get you going. Also, you can check the tests in **chat/tests/integration/** as they contain everything you need on how to work with the package.
