### ISSUE TITLE
Error on getting messages from a conversation.

### ISSUE THREAD

**Issue by bryandidur** [musonza/chat#37]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>'$.\"message_id\"' = `mc_messages`.`id` where `mc_messages`.`conversation_id` in ' at line 1 (SQL: select `notifications`.*, `mc_messages`.* from `mc_messages` inner join `notifications` on `notifications`.`data`->'$.\"message_id\"' = `mc_messages`.`id` where `mc_messages`.`conversation_id` in (1) order by `mc_messages`.`id` desc)

PHP: 7.0
MySQL: 5.6

**Comment by musonza** [comment]
Hey @bryandidur, you will need at least MySQL 5.7 to support json columns in the laravel notifications table.

**Comment by bryandidur** [comment]
Thank you. The problem was this.
Upgrading from MySQL 5.6 to 5.7 solved the problem, ;)
