### ISSUE TITLE
Getting SQL error 

### ISSUE THREAD

**Issue by jayant1993** [musonza/chat#39]
Hi Musonza,

I am getting an sql error when I used the getMessages method.

my code ::

 public function chats()
    {
    		$currentuser = Auth::user();

    		$conversations = Chat::getConversationBetween($currentuser, 1);

    		$messages = Chat::conversations()->for($currentuser)->limit(25)->page(1)->get();

    		//return view('chats',['conversation' => $conversations, 'messages' => $messages]);

    		//return $messages;
    }

it shows the below error ::

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."message_id"' = `mc_messages`.`id` where `mc_messages`.`conversation_id` in ' at line 1 (SQL: select `notifications`.*, `mc_messages`.* from `mc_messages` inner join `notifications` on `notifications`.`data`->'$."message_id"' = `mc_messages`.`id` where `mc_messages`.`conversation_id` in (1) order by `mc_messages`.`id` desc)

Please Suggest me something :)

**Comment by musonza** [comment]
What database and version are you using.

https://github.com/musonza/chat/issues/38

**Comment by jayant1993** [comment]
![screen shot 2018-01-06 at 10 12 46 pm](https://user-images.githubusercontent.com/7889708/34641750-c573dcac-f32e-11e7-85b3-6442dd98cb2d.png)

**Comment by spmsupun** [comment]
@musonza  even in that branch i'm getting the same error

**Comment by musonza** [comment]
Did you publish the new config file and set laravel_notifications to false? You also have to migrate the new table to be created

**Comment by spmsupun** [comment]
I've set  `'laravel_notifications'`  to  `false` and now it's working, so we cannot use laravel notification on this branch ?

**Comment by musonza** [comment]
You can use laravel notifications if your database supports json columns. Rather than having users use the older version i brought in the custom table i had in the first version so you can have an option
