### ISSUE TITLE
Broadcasting  ?

### ISSUE THREAD

**Issue by spmsupun** [musonza/chat#40]
Are you gonna implement broadcasting  ?

**Comment by musonza** [comment]
@spmsupun I haven't planned on it. However, I will look into that. If you would like to submit a PR that's ok too.

**Comment by spmsupun** [comment]
Okay, I'll give it a try

**Comment by musonza** [comment]
Sounds good. Otherwise i may have it done end of the week. There are some updates i was thinking to work on.

**Comment by spmsupun** [comment]
Is there any way to test the package before require to a laravel project ? Unit testing doesn't  seems working.

**Comment by musonza** [comment]
Yes there is a way to test using orchestra

```
    "require-dev": {
        "phpunit/phpunit": "~6.0",
        "orchestra/testbench": "3.5.*",
        "orchestra/database": "3.5.*"
    },
```

However, i have made updates and broadcasting works. Checkout the branch below and you should be able to run unit tests without a laravel project:

https://github.com/musonza/chat/tree/custom-notifications-broadcast

Run 
`composer install`

`vendor/bin/phpunit`

I still need to test a few things as far sending the broadcasts to a que.

**Comment by spmsupun** [comment]
funny, I was gonna use  testbench :)  okay I'm gonna check on that,
and other thing is in notification can you give user to add extra data ?
for example  current data looks like this:
`{"message_id":2,"conversation_id":4}`

but i want like this:
`{"message_id":2,"conversation_id":4,"some_name":"some_value"}`

otherwise I cannot identified each notification. it'll be conflict with mine.

**Comment by musonza** [comment]
yes i'm adding some transformers for the data returned and also working on this to be more configurable.

**Comment by spmsupun** [comment]
Ok thanks, tell me if you need any help

**Comment by musonza** [comment]
Thanks will do

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v2.1.0
