### ISSUE TITLE
Getting conversation and No. of unread messages

### ISSUE THREAD

**Issue by spmsupun** [musonza/chat#42]
How do i get conversations list from a user order by last updated, `Chat::commonConversations ` doesn't return eloquent instance. And is there a way to get No. of unread messages for a user ? or do we have do it by manually ?

**Comment by musonza** [comment]
conversations list

https://github.com/musonza/chat/issues/23

No. of unread messages for a user:
Let me verify this

**Comment by musonza** [comment]
https://github.com/musonza/chat#unread-messages-count

**Comment by spmsupun** [comment]
how do I sort messages by last updated date
` Chat::conversations($conversation)->for($user)->getMessages($perPage, $page)`
this return only first messages in a conversation, and its not return an elaquent instance

**Comment by spmsupun** [comment]
nevermind, found a solution `Chat::conversation($id)->getMessages(\Auth::user(), 25, 1, 'desc')`
