### ISSUE TITLE
JSON_EXTRACT function error

### ISSUE THREAD

**Issue by JJS4ntos** [musonza/chat#43]
Hi, bro
I try to use your chat and i've a little problem.
`JSON_EXTRACT function error `

I know its because i'm using a mysql version without that function, but, have a solution about it?
I can't change the version of mysql, my production are in a shared host.

**Comment by musonza** [comment]
working on a solution here https://github.com/musonza/chat/tree/custom-notifications-broadcast

**Comment by JJS4ntos** [comment]
![solution](https://user-images.githubusercontent.com/13887489/35683260-8908ccc0-074a-11e8-9189-8905c648005b.png)

Look that, not working...
In production the mysql version don't have that function, but it was used in development.

**Comment by musonza** [comment]
is that config file published in your config files because it doesn't see like it's following the configuration. I still have to merge this in a few days so use that branch just for testing

**Comment by musonza** [comment]
https://github.com/musonza/chat/releases/tag/v2.1.0
