### ISSUE TITLE
How to get new  messages ?

### ISSUE THREAD

**Issue by spmsupun** [musonza/chat#48]
for example if I'm in a conversation and last message id is 10 then there are new messages came and how i get the message(s) greater than 10.
and also there are no any function to get a one single message, and Message send function doesn't return the message that sent so i have to recall a function to get the last message.

**Comment by musonza** [comment]
‘$conversation->last_message();’

**Comment by musonza** [comment]
It does return the message you send `Musonza\Chat\Messages\Message`
<img width="484" alt="screen shot 2018-02-05 at 9 03 01 pm" src="https://user-images.githubusercontent.com/3452388/35842598-ffb841aa-0ab7-11e8-9dba-d8f7844eed41.png">

**Comment by spmsupun** [comment]
so we have do it manually using 'Message' class as a model right ?

**Comment by musonza** [comment]
@spmsupun https://github.com/musonza/chat/releases/tag/v2.1.1
