### ISSUE TITLE
User model in different namespace

### ISSUE THREAD

**Issue by vezlius** [musonza/chat#5]
I keep User model in CustomName\Models\User namespace. Is there easy way I can change the settings or should I check each file and change it manually?

How do I check if conversation already exists between two users? Method getConversationBetweenUsers() gives you one only if there is one, otherwise throws error "Undefined offset: 0", instead of null or false...

**Comment by musonza** [comment]
Give me a few hours and I will push an update with a config file where you can specify a User model. Will also address the getConversationBetweenUsers() issue.

**Comment by musonza** [comment]
This is taken care of. Check this pull request #6
