### ISSUE TITLE
How to run the test 

### ISSUE THREAD

**Issue by Bobyuan1015** [musonza/chat#56]
C:\Users\bob\innermessage\blog\vendor\musonza\chat>phpunit

Fatal error: Class 'Musonza\Chat\Tests\TestCase' not found in C:\Users\bob\innermessage\blog\vendor\musonza\chat\tests\Unit\ChatTest.php on line 8

what's wrong one my testing running

**Comment by musonza** [comment]
what version of the package do you have installed?

**Comment by Bobyuan1015** [comment]
I give up running test code. just directly invoke the APi your offered, they works. Thanks
