### ISSUE TITLE
Attach file in conversation

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#57]
Hello, How I can attach file to conversation in message?

**Comment by musonza** [comment]
You have to handle the uploads and specify the message type.
[send-a-message-of-custom-type](https://github.com/musonza/chat#send-a-message-of-custom-type)

Example:

The type can be anything you want like url, image, attachment. Anything that you will be able to translate on your UI side.

```
$attachment = 'http://example.com/img'; // an image or attachment you upload somewhere
$message = Chat::message($attachment)
		->type('image')
		->from($user)
		->to($conversation)
		->send(); 
```
