### ISSUE TITLE
How I can get model participant of conversation?

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#59]
Hello, please help me get participant of conversation. Not currently authorized user, are participant conversation.

**Comment by musonza** [comment]
Can you explain further? Not sure i understand.

**Comment by Dronax** [comment]
I want get recipient of conversation. How I can get it?

**Comment by musonza** [comment]
Assuming you have only 2 users and your id is `$my_id`
`
$recipient = $conversation->users()->where('user_id', '<>', $my_id)->first();
`

**Comment by Dronax** [comment]
Please see my function, this correctly? 

`    public function inbox() {
        $user = Auth::user();
        $conversations = Chat::commonConversations($user);
        //$LastMessages['partcipant'] = $conf->users[1];
        $LastMessages = [];
        $participant = [];

        foreach($conversations as $conf) {
            $LastMessages[] = Chat::conversations($conf)->for($user)->getMessages()->last();
            $participant[] = $conf->users()->where('user_id', '<>', $user->id)->first();;
        }

        //dd($participant);

        return view('inbox.index', compact('LastMessages', 'participant'));
    }`

**Comment by musonza** [comment]
You need to use this 

```
$messages = Chat::conversations()->for($user)->limit(25)->page(1)->get();
```

This gives you a list of all the conversations for the `$user` alongside the most recent message. Just like your inbox.

**Comment by Dronax** [comment]
Here's what I got: https://pastebin.com/fR7bPFD9 I can without loop get conversation messages and recepient?

**Comment by matthewborgcarr** [comment]
Hello, this is an awesome package.

I need to know how I can get all the messages the user is participating in?

Thanks
Matthew

**Comment by matthewborgcarr** [comment]
In more detail to my question above, I am creating an application where it displays a list of conversations (with the conversation_id, the sender, the receipient and the last message in the conversation).

Then using the selected conversation_id I get all the messages within that particular conversation.

How can I achieve this?

Thanks
Matthew

**Comment by musonza** [comment]
```php
$messages = Chat::conversation($conversation)->for($user)->getMessages();
```
https://github.com/musonza/chat-demo/blob/62e39992070b3a63053c43ad4e9a3191cd709d6d/app/Http/Controllers/ConversationController.php#L53
