### ISSUE TITLE
Cannot use the Chat Facade

### ISSUE THREAD

**Issue by jesephan** [musonza/chat#60]
Hello,

I'm using your package to create chat feature to my project.
I'm using Laravel 5.5 and I encounter issue when using the package chat facade.
Please check this [link](https://prnt.sc/idyx59) to see the error message.
Hope to hear your response/feedback about this issue.

Thanks

**Comment by musonza** [comment]
Appears you are not using the Facade correctly. 
```
'Chat' => Musonza\Chat\Facades\ChatFacade::class to your `config\app.php`
```
change `use Musonza\Chat\Chat;` in your `MessageController` to `use Chat;`

**Comment by jesephan** [comment]
I checked your package.json file seems you are using auto discovery?

**Comment by jesephan** [comment]
Okay thanks I thought no need for this when using laravel's package auto discovery.
