### ISSUE TITLE
Use pagination for chat

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#61]
Hello, How I can use default pagination for chat messages, conversations?

Method `paginate` not working.

`$conversations = Chat::conversations()->for($user)->paginate(10);`

**Comment by musonza** [comment]
Please look at the Readme for the correct methods:

https://github.com/musonza/chat#get-recent-messages

$messages = Chat::conversations()->for($user)->limit(25)->page(1)->get();

You want to use the above because the code has to take into consideration if you are using laravel notifications table or a custom table.

Otherwise look at this function that's being used.

```
    private function getConversationMessages($user, $perPage, $page, $sorting, $columns, $pageName)
    {
        if (Chat::laravelNotifications()) {
            return $this->messages()
                ->join('notifications', 'notifications.data->message_id', '=', 'mc_messages.id')
                ->where('notifications.notifiable_id', $user->id)
                ->orderBy('mc_messages.id', $sorting)
                ->paginate(
                    $perPage,
                    [
                        'notifications.read_at', 'notifications.notifiable_id', 'notifications.id as notification_id',
                        'mc_messages.*',
                    ],
                    $pageName,
                    $page
                );
        }

        return $this->messages()
            ->join('mc_message_notification', 'mc_message_notification.message_id', '=', 'mc_messages.id')
            ->where('mc_message_notification.user_id', $user->id)
            ->orderBy('mc_messages.id', $sorting)
            ->paginate(
                $perPage,
                [
                    'mc_message_notification.updated_at as read_at', 'mc_message_notification.user_id', 'mc_message_notification.id as notification_id',
                    'mc_messages.*',
                ],
                $pageName,
                $page
            );
    }
```

**Comment by Dronax** [comment]
How then I can integrate my pagination?

**Comment by musonza** [comment]
For getting messages in a specific conversation, this `Chat::conversations($conversation)->for($this->users[0])->getMessages($perPage, 4)` returns `Illuminate\Pagination\LengthAwarePaginator`. 

If you omit `->get()` as below you also get `Illuminate\Pagination\LengthAwarePaginator`
`$messages = Chat::conversations()->for($user)->limit(25)->page(1);`

**Comment by Dronax** [comment]
->page = ->paginate right?

**Comment by Dronax** [comment]
This is not working: 
`$messages = Chat::conversations()->for($user)->page(1);`

I get empty object.

**Comment by musonza** [comment]
This will call `paginate(10)` for you. it just makes the code expressive.
`
$conversations = Chat::conversations()->for($user)->limit(10)->page(1);
`
Email me and i will help you further. Email is on my profile.

**Comment by Dronax** [comment]
I get empty object.

Chat {#359 ▼
  #type: "text"
  #from: null
  #to: null
  #body: null
  #perPage: 1
  #page: 1
  +"conversation": Conversation {#357 ▼
    #table: "mc_conversations"
    #fillable: array:1 [▶]
    #casts: array:1 [▶]
    #prefix: "mc_"
    #connection: null
    #primaryKey: "id"
    #keyType: "int"
    +incrementing: true
    #with: []
    #withCount: []
    #perPage: 15
    +exists: false
    +wasRecentlyCreated: false
    #attributes: []
    #original: []
    #changes: []
    #dates: []
    #dateFormat: null
    #appends: []
    #dispatchesEvents: []
    #observables: []
    #relations: []
    #touches: []
    +timestamps: true
    #hidden: []
    #visible: []
    #guarded: array:1 [▶]
  }
  +"message": Message {#358 ▶}
  +"commandBus": CommandBus {#360 ▶}
  +"user": User {#348 ▶}
}
