### ISSUE TITLE
Pagination...

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#63]
I can't find mail on your profile..

Why pagination working only by request? Why I can't use pagination blade?

`    public function inbox(Request $request) {
        $user = Auth::user();
        //$conversations = Chat::commonConversations($user);
        //$LastMessages['partcipant'] = $conf->users[1];
        $conversations = Chat::conversations()->for($user)->limit(1)->page($request->get('page'))->get();
}`

**Comment by musonza** [comment]
The email should be available now

**Comment by Dronax** [comment]
Ok. I sended mail.

**Comment by musonza** [comment]
The other comment was a bit incorrect. Form the package this returns a paginator
```
        $paginator = Chat::conversations()
                    ->for($user)
                    ->page($page)
                    ->get();
```

**Comment by Dronax** [comment]
But where I can get $page variable? Only by `$request->get('page')`?

**Comment by musonza** [comment]
Page is the page number, 1,2,3...So you can send that in the request yes.
You can start by passing 1 then you track what next page to request for
next page.
