### ISSUE TITLE
Some issue while getting messages.

### ISSUE THREAD

**Issue by vivdub** [musonza/chat#64]
Hi,
I am using the following to fetch messages:
Chat::conversations($conversation)->for($user)->getMessages($perPage, $page)

But it throws an error.
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '&gt;'$.&quot;message_id&quot;' = `mc_messages`.`id` where `mc_messages`.`conversation_id` = ?' at line 1 (SQL: select count(*) as aggregate from `mc_messages` inner join `notifications` on `notifications`.`data`-&gt;'$.&quot;message_id&quot;' = `mc_messages`.`id` where `mc_messages`.`conversation_id` = 1 and `mc_messages`.`conversation_id` is not null and `notifications`.`notifiable_id` = 4)

Any help ?
Thanks

**Comment by musonza** [comment]
Your db doesn’t support json columns so in the package config file set laravel_notifications to false. However, if you have messages already the unread count and state will be off

**Comment by vivdub** [comment]
Thanks, I will check.
