### ISSUE TITLE
MessageWasSent event not working

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#67]
#66 
Hello, I have:

`Broadcast::channel('mc-chat-conversation.{conversation_id}', function($user) {
    return $user;
});`

App.js:

`
mounted() {
        Echo.private('mc-chat-conversation.' + this.convId)
            .listen('MessageWasSent', (e) => {
                console.log(e);
                this.chat.message.push(e.message);
                this.chat.user.push(e.user);
                this.chat.time.push(this.getTime());
                console.log(e);
            })
            .listenForWhisper('typing', (e) => {
                if(e.name != '')
                    this.typing = 'Набирает сообщение..';
                else
                    this.typing = null;
            });
    }
`

Controller:

`     broadcast(new MessageWasSent($message))->toOthers();`

But event not received data to other user, why??? console.log(e) get empty result.

I think, that event MessageWasSent not know, that need send message to other user. He can only receive a message? Why??

**Comment by musonza** [comment]
You don’t have to do the broadcast yourself. Just set the broadcast option in the config to true.

**Comment by Dronax** [comment]
/**
     * This will allow you to broadcast an event when a message is sent
     * Example:
     * Channel: private-mc-chat-conversation.2, 
     * Event: Musonza\Chat\Messages\MessageWasSent 
     */
    'broadcasts'            => true,

I have this

**Comment by Dronax** [comment]
Not working this:

        Echo.private('mc-chat-conversation.' + this.convId)
            .listen('MessageWasSent', (e) => {

**Comment by musonza** [comment]
```
Echo.private('mc-chat-conversation.' + this.convId) .listen('MessageWasSent'..,
```
You need the fully qualified name for `MessageWasSent` like `Musonza\Chat\Messages\MessageWasSent`

**Comment by Dronax** [comment]
Not working :(((

**Comment by Dronax** [comment]
Working. Sorry. But how I can get recipient?

**Comment by anurak-kg** [comment]
// channels.php
Broadcast::channel('mc-chat-conversation.{id}', function ($user, $id) {
    $userConversion = ConversationUser::where('user_id', $user->id)
        ->where('conversation_id', $id)
        ->first();
    return !is_null($userConversion);
});

js file
 let chanel = 'mc-chat-conversation.' + this.conversationId.toString();
      Echo.private(chanel)
      .listen('\\Musonza\\Chat\\Eventing\\MessageWasSent', (e) => {
            console.log(e);
      });

**Comment by Jaspur** [comment]
@Dronax figured out how to do it? cc #111
