### ISSUE TITLE
GetMessage in Descending order

### ISSUE THREAD

**Issue by harikarank** [musonza/chat#69]
Hi
How can in get count no of total messages?

Help to update the below function for to getMessages in Descending order
musonza\chat\src\Chat.php
![image](https://user-images.githubusercontent.com/8309169/36383581-892f32e4-15c7-11e8-88a1-4c3e9c408774.png)

So i can call this like
$msgs =Chat::conversations($conversation)->for($user)->getMessages(10,1,'desc');

**Comment by musonza** [comment]
That should return `LengthAwarePaginator` Try to dump the result from that function and see if you get the total.
