### ISSUE TITLE
Mark message is read function

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#70]
I have function:

    public function setMessagesSeen(Conversation $conversation, Request $request) {
    $v = Validator::make($request->all(), [
        'message' => 'required|string|max:4000',
    ]);

    $user = User::find(Auth::id());

    $conversations = Chat::conversation($conversation->id);

    //$message = Chat::conversations($conversations)->for($user)->getMessages()->where('body', $request->message)->where('user_id', '<>', $user->id);

    //$message->markRead();

    //var_dump($message); exit;

    broadcast(new MessageIsSeen($message));

    return response('ok'); }

I have a post request:

```
methods: {
    seenMessage() {
        if(this.message.length != 0) {
            axios.post('/setMessagesSeen/' + this.convId, {
                message: this.message,
            })
            .then( response => { $('li').removeClass('unread'); }) 
            .catch( response => { console.log(response) } )
        }
},
```

How I can correctly read message for users? I need add/remove class to div in app.js, when message is readed for user. But how check this and mark correctly read message, I need message id?

**Comment by musonza** [comment]
https://github.com/musonza/chat#mark-a-message-as-read
```php
Chat::messages($message)->for($user)->markRead();
```

**Comment by musonza** [comment]
Pass the message id to your controller from `this.message` then on the server use this to get the `message` model:
https://github.com/musonza/chat#get-a-message-by-id

**Comment by Dronax** [comment]
Message id how I can get?

**Comment by musonza** [comment]
this depends on how you setup your application. You should keep track of that from your messages list etc

**Comment by Dronax** [comment]
I don't have id message in my app

**Comment by musonza** [comment]
All messages returned from the methods listed in the README will have ids.
