### ISSUE TITLE
Compatibility issue with mariadb

### ISSUE THREAD

**Issue by gergo2007** [musonza/chat#75]
Hi

Im getting the fol;owing error:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."message_id"' = `mc_messages`.`id` where `mc_messages`.`conversation_id` = ?' at line 1 (SQL: select count(*) as aggregate from `mc_messages` inner join `notifications` on `notifications`.`data`->'$."message_id"' = `mc_messages`.`id` where `mc_messages`.`conversation_id` = 2 and `mc_messages`.`conversation_id` is not null and `notifications`.`notifiable_id` = 1)

Any tips fixing this?

Thanks

**Comment by musonza** [comment]
In the config file make this update `'laravel_notifications' => false`,

**Comment by gergo2007** [comment]
Thanks, works!
