### ISSUE TITLE
Event not broadcasting now..

### ISSUE THREAD

**Issue by Dronax** [musonza/chat#77]
Hello, Event MessageWasSent not broadcasting, I use:

`$message = Chat::message($request->message)
            ->from($user)
            ->to($conv)
            ->send();`

In config broadcasting sets to true.
My other events broadcast, but event MessageWasSent not.
Fix please!!

**Comment by musonza** [comment]
Are you checking for the fully qualified name Musonza\Chat\MessageWasSent
