### ISSUE TITLE
Soft delete

### ISSUE THREAD

**Issue by AttilaSzendi** [musonza/chat#79]
Is there any plans for the future to use soft deletes. I think it is a must have in this kind of feature.

**Comment by musonza** [comment]
yes working on that

**Comment by musonza** [comment]
https://github.com/musonza/chat/blob/5e04b33f7195a9ffe939d1267a01641b119d5e19/tests/Unit/MessageTest.php#L101

**Comment by diego-lipinski-de-castro** [comment]
has this been done? nothing about this in the documentation

**Comment by musonza** [comment]
@diego-lipinski-de-castro I don't think this was added to a conversation. Feel free to create a PR. Thanks
