### ISSUE TITLE
Chat::getConversationBetween returns always null

### ISSUE THREAD

**Issue by AEK-BKF** [musonza/chat#80]
Hi,
I'm using `Laravel 5.6.20`, `PHP 7.2.4`
I'm trying to get getConversationBetween between Auth and other user:
`dd(Chat::getConversationBetween(Auth::id(),$request->id));`
But it returns always null, even I have created conversation between them :
`$conversation = Chat::createConversation([$request->id]); `

> NB: No messages have been created yet, I've just create the conversation 

Regards

**Comment by musonza** [comment]
Could be you are passing same user_ids
