### ISSUE TITLE
Possibility to get unread messages per Conversation

### ISSUE THREAD

**Issue by exzib** [musonza/chat#82]
So for example

$conversation->unreadMessages->for(USER), rather than getting their total unread messages.

**Comment by exzib** [comment]
Fixed this myself by adding this function to Conversation.php

`     public function unreadNotifications($user)
     {
       $notifications = MessageNotification::where([['user_id', '=', $user->id], ['conversation_id', '=', $this->id], ['is_seen', '=', 0]])->get();

       return $notifications;
     }`

**Comment by musonza** [comment]
Sounds good. Do you mind making a PR so I can add that update?
