### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [musonza/chat#83]
Hi @musonza ,, I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by musonza** [comment]
Hi, sure you can. Thanks

**Comment by mirzazulfan** [comment]
Hi @musonza ,  I've designed a logo for your project. If you like it, you can use it. it's free. I'll send you files and pr. If you need anything change, let me know. Thanks
![chat](https://user-images.githubusercontent.com/36124339/40628010-93f30d28-62ec-11e8-8ec2-35f24eba3253.png)

**Comment by musonza** [comment]
Nice, looks great, you can create the PR with the blue logo as is at the bottom

**Comment by mirzazulfan** [comment]
Hi @musonza .. i've created a pr #84 please check. you can download all files (.SVG .PDF .PNG) here
[Drive](https://drive.google.com/drive/folders/1EpXA5UGqFGC6eHuOdsZG67-mAIhdwuAz)
thanks..

**Comment by musonza** [comment]
Thanks
