### ISSUE TITLE
Class 'Chat' not found

### ISSUE THREAD

**Issue by caiokawasaki** [musonza/chat#90]
I'm trying to implement this package in my application but I'm having problems.

I already added the Providers in the `config/app.php` file and even then the framework does not find the class.

```
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use Chat;

class MessageController extends BaseController
{
    protected $viewType = 'messages';

    public function index()
    {
        $this->setVariable('title', 'Mensagens');

        $conversations = Chat::conversations()->for(Auth::user()->id)->limit(25)->page(1)->get();;
        $this->setVariable('conversations', $conversations);

        return $this->viewRender('index');
    }
}
```

Am I forgetting to do something?

I'm using Laravel version 5.6.*

**Comment by Hirbod** [comment]
@caiokawasaki as you have been closing this thread, could you tell us how did you manage to fix this?

**Comment by caiokawasaki** [comment]
@Hirbod If I'm right, it was cache, Laravel's cache already deceived me many times. Try the following commands:

`composer dump -o`
`php artisan cache:clear`
