### ISSUE TITLE
PHPUnit tests failing

### ISSUE THREAD

**Issue by axe1987** [musonza/chat#92]
Hello,
first of all, nice plugin 👍 

But when using laravel dusk the phpunit tests for your chat plugin fail.
The message is that the class Eloquent can't be found in your file chat/src/Model.php.

I think the problem could be easily solved if you use `\Illuminate\Database\Eloquent\Model` to extend the model class, instead of an laravel alias.

Greets axe

**Comment by musonza** [comment]
Yeah that’s right, thanks. You can create a PR or I will update when I have time

**Comment by axe1987** [comment]
I would like to commit my branch with the changes discussed above. But I can't seem to be able to push it.
Since I usually use gitlab, I might just not know how the pull requests work. Or I need rights for this :)

Please explain^^

**Comment by musonza** [comment]
Create a fork of `https://github.com/musonza/chat`, push your changes there and create a pull request from those changes.
