### ISSUE TITLE
Getting latest messages

### ISSUE THREAD

**Issue by axe1987** [musonza/chat#94]
Hi,

how would you get the latest messages of the current conversation?
Let's say I only want to load the last 10 messages (last by created_at). And then I want a Ajax call to (the same or another action in the controller) to load the next 10 items of the conversation.
 Furthermore I always want the latest message at the beginning of the collection/pagination.

Can you give me a hint  how your plugin handles this ??

**Comment by EfosaSO** [comment]
@axe1987 here's a hack for you. In `vendors/musonza/chat/src/Traits` change the `getConversationMessages` method to this:

`$total = $paginationParams['pageName'] - $paginationParams['perPage'] + 1;
        $messages = $this->messages()
            ->join('mc_message_notification', 'mc_message_notification.message_id', '=', 'mc_messages.id')
            ->where('mc_message_notification.user_id', $user->id)
            ->where('mc_messages.id', '>=', $total);
        $messages = $deleted ? $messages->whereNotNull('mc_message_notification.deleted_at') : $messages->whereNull('mc_message_notification.deleted_at');
        $messages = $messages->orderBy('mc_messages.id', $paginationParams['sorting'])
            ->paginate(
                $paginationParams['perPage'],
                [
                    'mc_message_notification.updated_at as read_at',
                    'mc_message_notification.deleted_at as deleted_at',
                    'mc_message_notification.user_id',
                    'mc_message_notification.id as notification_id',
                    'mc_messages.*',
                ],
                $paginationParams['pageName'],
                $paginationParams['page']
            );

        return $messages;`

The `pageName` parameter in the `$paginationParams` can be set to the last ID for the record you want to retrieve, that you are only pulling in the latest x records that you need.
