### ISSUE TITLE
How to deal with soft deleted users?

### ISSUE THREAD

**Issue by caiokawasaki** [musonza/chat#96]
I've implemented this package in my application, and I use some viewComposers. I was testing today and noticed that the entire application crash for not finding deleted users. How should I correct this?

Here is a example:
```
class MessagesViewComposer
{
    public function compose(View $view)
    {
        $user = auth()->user();

        $conversations = Chat::conversations()->for($user)->get();

        $array = [];

        $unreadConversationsCount = 0;

        foreach($conversations->all() as $key => $conversation){
            $unreadNotifications = $conversation->unreadNotifications($user);

            $array[$key] = [
                'user' => $conversation->users->firstWhere('id', '!=', $user->id)->toArray(),
                'last_message' => [
                    'body' => $conversation->last_message->body,
                    'type' => $conversation->last_message->type,
                    'is_seen' => $conversation->last_message->is_seen,
                    'updated_at' => $conversation->last_message->updated_at->diffForHumans()
                ],
                'unread_notifications' => count($unreadNotifications)
            ];

            if(count($unreadNotifications)){
                $unreadConversationsCount++;
            }
        }

        $view->with('conversations', $array);
        $view->with('unreadConversationsCount', $unreadConversationsCount);
        $view->with('messageReadPermission', 'admin.messages.read');
    }
}
```

Error: Call to a member function toArray() on null (View: /Users/caiokawasaki/www/ecco/resources/views/admin/layouts/master.blade.php) (View: /Users/caiokawasaki/www/ecco/resources/views/admin/layouts/master.blade.php)

The problem is that in several places I refer to the deleted user.  How should I correct this?

**Comment by musonza** [comment]
Can you try `$conversation->users->withTrashed()` to get the deleted users as well

**Comment by caiokawasaki** [comment]
Just get this error:
Method Illuminate\Database\Eloquent\Collection::withTrashed does not exist. (View: /Users/caiokawasaki/www/ecco/resources/views/admin/layouts/master.blade.php) (View: /Users/caiokawasaki/www/ecco/resources/views/admin/layouts/master.blade.php)

**Comment by musonza** [comment]
oh for relationship it's  missing parenthesis `$conversation->users()->withTrashed()`
